language: node_js
sudo: false
node_js:
- '4.2'
before_install:
- cp ci/travis-ci.sh $HOME/
- chmod +x $HOME/travis-ci.sh
#- cp ci/cfindex.sh $HOME/
#- chmod +x $HOME/cfindex.sh
#- cp ci/index-gen.sh $HOME/
#- chmod +x $HOME/index-gen.sh
- $HOME/travis-ci.sh before-install
before_script:
- $HOME/travis-ci.sh before-script
script:
- $HOME/travis-ci.sh script
after_script:
- $HOME/travis-ci.sh after-script
after_success:
- $HOME/travis-ci.sh after-success
before_deploy:
#- $HOME/travis-ci.sh before-deploy
#- cd built
after_deploy:
#- $HOME/travis-ci.sh after-deploy
#deploy:
#- provider: releases
#  api_key:
#    secure: ay6Y16MbnOFAfyxBgW/C4Z0V1QLj9h9t4pLXPziDw3+KE4Olh3qOxVP5HNEF5VpwNBmXzKeRGlC88LGn93sW8x+A5CfYNZxBoNWGASUSkuRfoAB6oLaqAwJlm9GViq4m/qtuFzJJ5+ZpSWw6JE1GZnS/hzgcYZVdKyhlf4PA4XA=
#  file:
#  - kalabox2-win64-$TRAVIS_TAG.zip
#  - kalabox2-osx64-$TRAVIS_TAG.tar.gz
#  - kalabox2-linux64-$TRAVIS_TAG.tar.gz
#  skip_cleanup: true
#  on:
#    repo: kalabox/kalabox-ui
#    all_branches: true
#    tags: true
#- provider: cloudfiles
#  username: kalamuna
#  api_key:
#    secure: kZ1n6iNPWbs9ENeH4bJoEwKoJ0jn/V1tY+BwNXMeVsf86theVeePZTqRKaAz76IpHVRwZnFVPbzjzdYKEm8Qnz45rUnfwyBDsn+/RC/76i09AnZ/oeX+21h9IoabA5N7cMg4Gu10eFmjQDvJKm8z1v+jZB6A1tP1sXyi+Q2xazQ=
#  region: ord
#  container: kb2
#  skip_cleanup: true
#  on:
#    repo: kalabox/kalabox-ui
#    branch: master
cache:
  directories:
  - node_modules
notifications:
  irc:
  - chat.freenode.net#kalabox
  email:
    recipients:
    - mike@kalabox.io
    - riley@kalabox.io
    - alec@kalabox.io
    on_success: always
env:
  global:
    secure: Zx94toqGScUIRZ/LBx0h8L/y/Lff4YFV+5QMbec+73ZpQMlATLqa4bl0PFy9Cp2RNNN9ljqkMoUQLanBetaPdL3Wxqo6qUloCrnPN/mzIVrL/mbbmG7bz6dVjtcB3CmheYTmdSBjNv+5n/gtb6DWfuX5Pdd9gVxruRqwHT3tW3g=
